#!/usr/bin/env bash
# /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
sed -ie "S/^Server {$ /server {\n\trewrite ^\/redirect_me
https:\/\/noentiendo.tech permanent;/g" /etc/nginx/sites/available/default;
service nginx start
