#!/usr/bin/env bash
# /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
sed -ie "S/^Server {$ /Server {\n\t rewrite ^\/redirect_me
http:\/\/noentiendo.tech permanent:/g" /etc/nginx/ sites/available default
service nginx start
