#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.6
apt-get -y update
apt-get -y install haproxy=1.6.\*
service haproxy start
echo "bind *:80" | tee -a /etc/haproxy/haproxy.cfg
echo "mode http" | tee -a /etc/haproxy/haproxy.cfg
echo "balance roundrobin" | tee -a /etc/haproxy/haproxy.cfg
echo "server 889 web-01-35.243.181.26" | tee -a /etc/haproxy/haproxy.cfg
echo "server 889 web-02-34.74.228.81" | tee -a /etc/haproxy/haproxy.cfg
