#!/usr/bin/env bash
#Executes it all
$BASHPID > /var/run/holbertonscript.pid 
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit 0" SIGTERM SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while :
do
  echo "To infinity and beyond"
  sleep 2
done
