#!/usr/bin/env bash
#Displays Holberton School 10 times with a condition
hbs='Holberton School'
i=0
while [ $i -lt 10 ]
do
  if [ $i -eq 9 ]
  then
    echo "Hi"
  fi
  echo "$hbs"
  i=$((i + 1))
done
