#!/usr/bin/env bash
# Debugging 2 
pkill nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx start
